[profile.default]
# Project
# https://book.getfoundry.sh/reference/config/project
src = 'contracts'
test = 'test'
script = 'script'
no_match_test = "testDiff"
out = 'out'
libs = ['node_modules', 'lib']
cache = true
cache_path = 'cache'
force = false
evm_version = 'cancun'
line_length = 100

# Compiler
# https://book.getfoundry.sh/reference/config/solidity-compiler
libraries = []
auto_detect_solc = true
solc_version = '0.8.25'

# 2462: Visibility for constructor is ignored
ignored_error_codes = [2462]
# set optimizer to true when deploying to mainnet
optimizer = false
optimizer_runs = 100
via_ir = false
bytecode_hash = 'ipfs'

# Testing
# https://book.getfoundry.sh/reference/config/testing
verbosity = 0
ffi = true
fs_permissions = [
  { access = "read", path = "../" },
  { access = "read", path = "./out" },
  { access = "read-write", path = "./test/generated/" },
  { access = "read-write", path = "./oscillation_data.csv" },
]
ignored_warnings_from = [
  "test",
  "contracts/interfaces/IMockFBeanstalk.sol",
  "contracts/mocks/",
]
gas_reports = ['*']
# Cache to `$HOME/.foundry/cache/<chain id>/<block number>`.
no_storage_caching = false

# Exclude deployment tests so CI works
no_match_contract = "Legacy"

[profile.differential]
match_test = "testDiff"
no_match_test = "a^"

[profile.default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'

[rpc_endpoints]
mainnet = "${FORKING_RPC}"

[invariant]
runs = 4
depth = 2048
fail_on_revert = true
